name: Publish liotbchain to pypi.org
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Ensure this permission is set
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Install Build package
        run: |
          python3 -m pip install --upgrade build && python3 -m build

      # - name: Run Tests
      #   run: | 
      #     python3 -m pip install -r requirements.txt
      #     pytest

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}